# Generated by Django 3.2.9 on 2021-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('situation', models.CharField(max_length=15)),
                ('solde', models.IntegerField(default=0)),
                ('penalites', models.IntegerField(default=0)),
            ],
        ),
    ]
