# Generated by Django 3.2.5 on 2021-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_livre_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='situation',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='penalites',
        ),
        migrations.RemoveField(
            model_name='client',
            name='solde',
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=20),
        ),
    ]
