# Generated by Django 3.2.5 on 2021-12-02 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20211202_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='categorie',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 16, 40, 58, 245367)),
        ),
        migrations.AddField(
            model_name='livre',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='empruntable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livre',
            name='support',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='supprime_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='theme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(default='plein tarif', max_length=15),
        ),
        migrations.AlterField(
            model_name='livre',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='nomAuteur',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prenomAuteur',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateField(default=datetime.datetime(2021, 12, 2, 16, 40, 58, 245367))),
                ('deadline', models.DateField(blank=True, null=True)),
                ('paye_le', models.DateField(blank=True, null=True)),
                ('raison', models.CharField(max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprunte_le', models.DateField(default=datetime.datetime(2021, 12, 2, 16, 40, 58, 245367))),
                ('retour_max_le', models.DateField(default=datetime.datetime(2022, 1, 1, 16, 40, 58, 245367))),
                ('rendu_le', models.DateField(blank=True, null=True)),
                ('en_retard', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.livre')),
            ],
        ),
    ]
