# Generated by Django 3.2.5 on 2021-12-02 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211202_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='disponibilite',
            new_name='disponible',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='emprunte_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 16, 54, 59, 46563)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='retour_max_le',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 16, 54, 59, 46563)),
        ),
        migrations.AlterField(
            model_name='livre',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 16, 54, 59, 46563)),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 16, 54, 59, 46563)),
        ),
    ]
