# Generated by Django 3.2.5 on 2021-12-02 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211202_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='emprunte_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 17, 1, 56, 530157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='retour_max_le',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 17, 1, 56, 530157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='livre',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 17, 1, 56, 530157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 18, 1, 56, 538540)),
        ),
    ]
