# Generated by Django 3.2.9 on 2021-12-03 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20211202_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='emprunte_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 8, 8, 783889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='retour_max_le',
            field=models.DateField(default=datetime.datetime(2022, 1, 2, 8, 8, 8, 783901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='livre',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 8, 8, 783139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 8, 8, 784186, tzinfo=utc)),
        ),
    ]
