# Generated by Django 3.2.9 on 2021-12-03 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20211203_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='emprunte_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 23, 18, 67775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='retour_max_le',
            field=models.DateField(default=datetime.datetime(2022, 1, 2, 8, 23, 18, 67789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='livre',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 23, 18, 66997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 23, 18, 68079, tzinfo=utc)),
        ),
    ]
