# Generated by Django 3.2.9 on 2021-12-03 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20211203_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='emprunte_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 24, 1, 751695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='retour_max_le',
            field=models.DateField(default=datetime.datetime(2022, 1, 2, 8, 24, 1, 751706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='livre',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 24, 1, 750965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='cree_le',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 24, 1, 751987, tzinfo=utc)),
        ),
    ]
